// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_forts_et_campagnes = "CgkIi7nLgfQPEAIQBw"; // <GPGSID>
        public const string achievement_citadelle_et_chteau = "CgkIi7nLgfQPEAIQCQ"; // <GPGSID>
        public const string achievement_parmi_nous = "CgkIi7nLgfQPEAIQCg"; // <GPGSID>
        public const string achievement_lumineux = "CgkIi7nLgfQPEAIQAA"; // <GPGSID>
        public const string achievement_brillant = "CgkIi7nLgfQPEAIQAQ"; // <GPGSID>
        public const string achievement_tincelant = "CgkIi7nLgfQPEAIQBA"; // <GPGSID>
        public const string achievement_triomphant = "CgkIi7nLgfQPEAIQCw"; // <GPGSID>
        public const string achievement_champs_et_villages = "CgkIi7nLgfQPEAIQCA"; // <GPGSID>
        public const string achievement_clatant = "CgkIi7nLgfQPEAIQAg"; // <GPGSID>
        public const string achievement_radieux = "CgkIi7nLgfQPEAIQBQ"; // <GPGSID>
        public const string achievement_champ_de_bataille = "CgkIi7nLgfQPEAIQBg"; // <GPGSID>
        public const string achievement_rayonnant = "CgkIi7nLgfQPEAIQAw"; // <GPGSID>

}

